[workspace]
authors = ["Sydney <1607170145@qq.com>"]
channels = ["conda-forge"]
name = "OptiSoft"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
aiomysql = ">=0.2.0,<0.3"
river = ">=0.13.0,<0.14"
pymoo = ">=0.6.1.5,<0.7"
fastapi = ">=0.121.2,<0.122"

[pypi-dependencies]
pyaedt = { version = ">=0.22.1, <0.23", extras = ["all"] }
pyside6-fluent-widgets = { version = ">=1.9.2, <2", extras = ["full"] }
pyside6-essentials = ">=6.9.3, <7"
pyside6-addons = ">=6.9.3, <7"
numpy = "*"
